### ISSUE TITLE
Email validity checker for class registration

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/cpinitiative#103]
to prevent people from not receiving emails because of a typo

**Comment by Fury-101** [comment]
would this be done by sending a confirmation email to the address inputted?

**Comment by maggie-j-liu** [comment]
i think that would add too much friction -- for some more context on this issue, it was caused bc someone mistyped .com as ,com. i think changing the input into an email input instead of a text input would be good enough since it should catch cases like this

**Comment by Fury-101** [comment]
oh, thought that was already the case from skimming through the code.
